TaskList/Models/ToDo.cs
namespace TaskList.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        public string Content { get; set; }
    }
}

TaskList/Controllers/TaskListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Template;
using Microsoft.EntityFrameworkCore;
using TaskList.Database;
using TaskList.Models;

namespace TaskList.Controllers
{
    public class TaskListController : Controller
    {
        private readonly DataContext _context;

        public TaskListController(DataContext context)
        {
            _context = context;
        }

        //GET method        
        public async Task<ActionResult> Index()
        {
            IQueryable<ToDo> items = from i in _context.taskLists orderby i.Id select i;

            List<ToDo> list = await items.ToListAsync();

            return View(list);
        }

        //GET create        
        public IActionResult Create ()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ToDo item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();              

                return RedirectToAction("Index");
            }

            return View(item);
        }

        //GET method        
        public async Task<ActionResult> Edit(int id)
        {
            ToDo? item = await _context.taskLists.FindAsync(id);
            if (item== null)
            {
                return NotFound();
            }

            return View(item);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ToDo item)
        {
            if (ModelState.IsValid)
            {
                _context.Update(item);
                await _context.SaveChangesAsync();                

                return RedirectToAction("Index");
            }

            return View(item);
        }
        
        //GET
        public async Task<ActionResult> Delete(int id)
        {
            ToDo? item = await _context.taskLists.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            else
            {
                _context.taskLists.Remove(item);
                await _context.SaveChangesAsync();
            }            

            return RedirectToAction("Index");
        }
    }
}

TaskList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="TaskList" asp-action="Index">TaskList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskList/Views/TaskList/Create.cshtml
@model TaskList.Models.ToDo

@{
    ViewData["Title"] = "Create";
}

<h1>Add a task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskList/Views/TaskList/Edit.cshtml
@model TaskList.Models.ToDo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit the task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskList/Views/TaskList/Index.cshtml
@model IEnumerable<TaskList.Models.ToDo>

@{
    ViewData["Title"] = "Index";
}

<h1>Task Manager</h1>

<p>
    <a asp-action="Create">Add new item to the list</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>